// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRGS.Infrastructure.Data;

#nullable disable

namespace SRGS.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727115422_UpdateAttachmentToStoreFileData")]
    partial class UpdateAttachmentToStoreFileData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SRGS.Application.Common.Models.UserRoleRow", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("USER_ROLE", (string)null);
                });

            modelBuilder.Entity("SRGS.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expires_on_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_REFRESH_TOKEN_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_REFRESH_TOKEN_user_id");

                    b.ToTable("REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Approvals.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("approval_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("approval_type");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("approver");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("decision");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_APPROVAL_request_id");

                    b.ToTable("APPROVAL", null, t =>
                        {
                            t.HasCheckConstraint("CK_APPROVAL_TYPE_decision", "approval_type IN ('Stakeholder','Managerial')");

                            t.HasCheckConstraint("CK_APPROVAL_decision", "decision IN ('Approved','Rejected','Pending')");
                        });
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Attachments.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("file_data");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_ATTACHMENT_request_id");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("ATTACHMENT", null, t =>
                        {
                            t.HasCheckConstraint("CHK_ATTACHMENT_FILE_SIZE", "file_size > 0 AND file_size <= 5242880");
                        });
                });

            modelBuilder.Entity("SRGS.Domain.Requests.History.ChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("change_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeOperation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("change_operation");

                    b.Property<string>("ChangeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int")
                        .HasColumnName("changed_by");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_CHANGE_HISTORY_request_id");

                    b.ToTable("CHANGE_HISTORY", null, t =>
                        {
                            t.HasCheckConstraint("CK_CHANGE_operation", "change_operation IN ('Add','Update','Delete')");

                            t.HasCheckConstraint("CK_CHANGE_type", "change_type IN ('Rule Set','Model','Form Designer','Workflow','Script','Catalog Item','Integration')");
                        });
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Lookups.ModuleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("module_name");

                    b.HasKey("Id");

                    b.HasIndex("ModuleName")
                        .IsUnique();

                    b.ToTable("MODULE_TYPE", (string)null);
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Lookups.RequestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("REQUEST_TYPE", (string)null);
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Notes.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("description_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_text");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_DESCRIPTION_request_id");

                    b.ToTable("DESCRIPTION", (string)null);
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int")
                        .HasColumnName("recipient");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_NOTIFICATION_request_id");

                    b.ToTable("NOTIFICATION", null, t =>
                        {
                            t.HasCheckConstraint("CK_NOTIFICATION_status", "status IN ('Pending','Sent','Failed')");
                        });
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_end");

                    b.Property<DateTimeOffset?>("ActualStart")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_start");

                    b.Property<int?>("AssignedBusinessAnalystId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_ba");

                    b.Property<int?>("AssignedDeveloperId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_developer");

                    b.Property<string>("BusinessJustification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_justification");

                    b.Property<DateTimeOffset?>("CloseTimeUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("close_time");

                    b.Property<DateOnly>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS DATE)");

                    b.Property<string>("CurrentBehavior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_behavior");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<byte?>("DevelopmentProgress")
                        .HasColumnType("tinyint")
                        .HasColumnName("development_progress");

                    b.Property<decimal?>("EstimatedEffort")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("estimated_effort");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expected_behavior");

                    b.Property<int>("ImpactedModuleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("impacted_module_id");

                    b.Property<DateTimeOffset>("OpenTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("open_time")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Logging")
                        .HasColumnName("phase");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Low")
                        .HasColumnName("priority");

                    b.Property<string>("RequestCode")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("request_code")
                        .HasComputedColumnSql("CAST('RF-' + CONVERT(VARCHAR(8), created_date, 112) + '-' + RIGHT('0000' + CAST(request_id AS VARCHAR(10)), 4) AS NVARCHAR(50))", true);

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("UnderAnalysis")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("UatResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uat_result");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBusinessAnalystId");

                    b.HasIndex("AssignedDeveloperId");

                    b.HasIndex("ImpactedModuleTypeId")
                        .HasDatabaseName("IX_REQUEST_impacted_module_id");

                    b.HasIndex("RequestTypeId")
                        .HasDatabaseName("IX_REQUEST_type_id");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("IX_REQUEST_requested_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_REQUEST_status");

                    b.ToTable("REQUEST", null, t =>
                        {
                            t.HasCheckConstraint("CK_REQUEST_priority", "priority IN ('Low','Medium','High','Critical')");

                            t.HasCheckConstraint("CK_REQUEST_progress", "development_progress BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_REQUEST_uat", "uat_result IN ('Passed','Failed','Pending')");
                        });
                });

            modelBuilder.Entity("SRGS.Domain.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("ROLE", (string)null);
                });

            modelBuilder.Entity("SRGS.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("family_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SubDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sub_department");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("SRGS.Application.Common.Models.UserRoleRow", b =>
                {
                    b.HasOne("SRGS.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SRGS.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REFRESH_TOKEN_USER");
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Approvals.Approval", b =>
                {
                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_APPROVAL_USER");

                    b.HasOne("SRGS.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_APPROVAL_REQUEST");
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Attachments.Attachment", b =>
                {
                    b.HasOne("SRGS.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ATTACHMENT_REQUEST");

                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ATTACHMENT_USER");
                });

            modelBuilder.Entity("SRGS.Domain.Requests.History.ChangeHistory", b =>
                {
                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CHANGE_USER");

                    b.HasOne("SRGS.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHANGE_REQUEST");
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Notes.Description", b =>
                {
                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DESCRIPTION_USER");

                    b.HasOne("SRGS.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DESCRIPTION_REQUEST");
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Notifications.Notification", b =>
                {
                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RECIPIENT");

                    b.HasOne("SRGS.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICATION_REQUEST");
                });

            modelBuilder.Entity("SRGS.Domain.Requests.Request", b =>
                {
                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedBusinessAnalystId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_REQUEST_BA");

                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedDeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_REQUEST_DEVELOPER");

                    b.HasOne("SRGS.Domain.Requests.Lookups.ModuleType", null)
                        .WithMany()
                        .HasForeignKey("ImpactedModuleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REQUEST_MODULE");

                    b.HasOne("SRGS.Domain.Requests.Lookups.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REQUEST_TYPE");

                    b.HasOne("SRGS.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REQUEST_REQUESTER");
                });
#pragma warning restore 612, 618
        }
    }
}
